### ISSUE TITLE
publications listing needs style tweaks

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#199]
_Issues identified in reviewing [scrumdo story 170 (Create a "publications listing")](https://www.scrumdo.com/projects/story_permalink/1105584):_

## 1. Image file size

We appear to be loading the full-size lead image here. Can we not grab a smaller version (which would get cached) to speed page performance?

## 2. In-page image size constraints

Image sizing is not quiet right if we want to avoid trapping whitespace on portrait images like this: 

![screen shot 2016-12-21 at 3 55 15 pm](https://cloud.githubusercontent.com/assets/263285/21407423/ee6df266-c795-11e6-9a7b-1a7af4bdeae5.png)

I think that by removing the ```width``` and ```max-height``` CSS declarations on ```.PublicationCardImage img``` we would get something cleaner that still behaves:

![screen shot 2016-12-21 at 4 00 25 pm](https://cloud.githubusercontent.com/assets/263285/21407733/a54b992a-c796-11e6-8829-c48b67735f8c.png)

## 3. Responsive collapse behaviors

There is a regime in which what's in place now doesn't work very nicely yet, e.g.:

![screen shot 2016-12-21 at 4 02 30 pm](https://cloud.githubusercontent.com/assets/263285/21407792/eebe251e-c796-11e6-9cb2-e4e80bd6b6e5.png)

This is the bit of CSS that is trying to manage the responsive collapse:

```css
@media screen and (max-width: 1160px) .PublicationCard {
    margin: 2%;
    width: 42%;
    height: 200px;
}
```

I think I'd be happier with what happens when we remove the ```width``` and ```height``` directives from that ```@media``` section:

```css
@media screen and (max-width: 1160px) .PublicationCard {
    margin: 2%;
}
```

which should yield something like this:

![screen shot 2016-12-21 at 4 07 51 pm](https://cloud.githubusercontent.com/assets/263285/21407933/a92e4438-c797-11e6-8783-d4a3d8b53c81.png)
