### ISSUE TITLE
Adjust opacity of overlay text block on home page slider: 0.5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#253]
> On the home page, the slider uses white text with a transparent background on a variation of images. While some of the images pass contrast guidelines, others do not. One solution for this would be increasing the opacity percentage or changing to a solid background behind the text.

![screen shot 2018-04-24 at 4 02 52 pm](https://user-images.githubusercontent.com/263285/39214658-d79b0918-47da-11e8-8075-566a493831c4.png)

Traceability: [Microassist Report 1 > WCAG Compliance > Color Contrast](https://docs.google.com/document/d/10cfUFx-o_kSGBFKCe4MtL45cyc-c-Gwaz3Dxlrp8Qgg/edit#bookmark=id.fg49504ke5mr)

WCAG 2.0: [1.4.3 Contrast (Minimum)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html): The visual presentation of texts and images of text has a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. 14 point and bold or larger, or 18 point and larger. (Level AA)

**Comment by paregorios** [comment]
See also #254

**Comment by paregorios** [comment]
Change the following CSS rules in isaw.theme/isaw/theme/static/theme.css:

```css
#content #slider .slide .slideroverlay {top: 50%; width:80vw; max-width: 50em; padding:40px 20px 20px; border: none; display:table; background-color: rgba(57, 48, 46, 0.5); transition: all 0.75s ease-in-out;}
#content #slider .slide .slideroverlay:hover {background-color: rgba(57, 48, 46, 0.8);}
```
so that the alpha values in the background-color rgba specifications are 0.8 and 1.0, respectively.
