### ISSUE TITLE
captioned images do not resize for narrow browser/mobile widths

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#419]
It would appear that CSS modifications like:

```css
span.captioned {
    max-width: 100%;
    max-height: auto;
}
```

would resolve the problem.
